
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev -w api

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev -w ui

  firestore-emulator:
    image: google/cloud-sdk:emulators
    platform: linux/amd64
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default:
    name: unsung-heroes-network
